---
name: 'Sync Notion with Github Issues'
description: |
  Syncs the `notion-database-id` with the P0 issues from the `github-repo` repository.
inputs:
  github-token:
    description: 'Requires repo permission'
    required: true
  notion-token:
    description: 'For modifying + reading database'
    required: true
  notion-database-id:
    description: 'The database to modify'
    required: true

# REQUIRES AT MINIMUM
# on:
#   issues:
#     types: [opened, reopened, labeled, unlabeled, edited, closed]

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v2
      with:
        path: ./integrations/notion-github-sync/node_modules
        key: modules-${{ hashFiles('package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci --ignore-scripts
      shell: bash
      working-directory: ./integrations/notion-github-sync
    - name: Start synchronization
      shell: bash
      run: node ./index.js
      working-directory: ./integrations/notion-github-sync
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        NOTION_TOKEN: ${{ inputs.notion-token }}
        NOTION_DATABASE_ID: ${{ inputs.notion-database-id }}
        GITHUB_REPO: ${{ github.repository }}
